version: '3.8'
services:
  user-service:
    container_name: user_mysql_db
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - user_mysql_db:/var/lib/mysql
volumes:
  user_mysql_db:
    external: false